### ISSUE TITLE
Document how to login as guest user

### ISSUE THREAD

**Issue by julioz** [gocd-contrib/gocd-groovy-dsl-config-plugin#259]
The [README](https://github.com/gocd-contrib/gocd-groovy-dsl-config-plugin/blob/master/README.md) mentions one can check a usage of this plugin if they login as the "guest user" on build.gocd.org. Can you please add a small sentence (or link) to how that can be done?

**Comment by arvindsv** [comment]
Hello! There is usually a plugin on build.gocd.org, which adds a "Guest" button, but it seems to be gone ... maybe because it is built with a wrong version of Java or something. For now, you can log in using the username "view" and password "password" (it is meant to be accessible, so the password is no big secret and mentioned previously).

I think, in this documentation, it can just show an image of that pipeline group. Once you see that group in build.gocd.org, you'll see what I mean. I think we can replace that reference to build.gocd.org in the README with an image.

**Comment by julioz** [comment]
@arvindsv I still like the possibility of logging in and playing around with GoCD's UI, checking the dashboards and pipelines, etc. If `view/password` are valid credentials (and remain so), could we instead alter the README to mention these instead of the "guest mode"?

**Comment by arvindsv** [comment]
That's fair. I tried to see why the guest login plugin did not show up. Need to look deeper. The username/password combination _should_ continue to be valid, but the button should be easier for everyone.

**Comment by arvindsv** [comment]
I see that the guest login button is back! Closing this. :)

PS: I didn't fix it. Someone / upgrade must have fixed it.

**Comment by julioz** [comment]
Thanks - even though I still think providing an alternative in the README (if this ever happens again) could prevent others from opening similar issues.
